export const mockData = [
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    isWaitByCustomer: false,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: false, 
    isVacuming: true, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Proses Pengerjaan'
  },
  { 
    noPolisi: 'B 321 ABC', 
    namaPelanggan: 'Jean Doe', 
    type: 'Inova', 
    isWaitByCustomer: true,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: true, 
    isVacuming: false, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Final Inspection'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    isWaitByCustomer: false,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: true, 
    isVacuming: true, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Tunggu Penyerahan'
  },
  { 
    noPolisi: 'B 321 ABC', 
    namaPelanggan: 'Jean Doe', 
    type: 'Inova', 
    isWaitByCustomer: true,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: true, 
    isVacuming: false, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Proses Cuci'
  },
  { 
    noPolisi: 'B 321 ABC', 
    namaPelanggan: 'Jean Doe', 
    type: 'Inova', 
    isWaitByCustomer: true,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: false, 
    isVacuming: false, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Final Inspection'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    isWaitByCustomer: false,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: true, 
    isVacuming: true, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Proses Pengerjaan'
  },
  { 
    noPolisi: 'B 321 ABC', 
    namaPelanggan: 'Jean Doe', 
    type: 'Inova', 
    isWaitByCustomer: true,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: false, 
    isVacuming: false, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Final Inspection'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    isWaitByCustomer: false,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: true, 
    isVacuming: true, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Tunggu Penyerahan'
  },
  { 
    noPolisi: 'B 321 ABC', 
    namaPelanggan: 'Jean Doe', 
    type: 'Inova', 
    isWaitByCustomer: true,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: true, 
    isVacuming: false, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Proses Cuci'
  },
  { 
    noPolisi: 'B 321 ABC', 
    namaPelanggan: 'Jean Doe', 
    type: 'Inova', 
    isWaitByCustomer: true,
    pekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    isWashing: true, 
    isVacuming: false, 
    timeIn: '13:30', 
    timeOut: '15:00', 
    foreman: 'John Doe',
    teknisi: 'John Doe',
    status: 'Final Inspection'
  },
]

export const progresData = [
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Tunggu Penyerahan',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Proses Pengerjaan',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Final Inspection',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Proses Cuci',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Tunggu Penyerahan',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Proses Pengerjaan',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Final Inspection',
    estimasiSelesai: '15:00', 
  },
]

export const welcomeData = [
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
]
