export const mockData = [
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Proses Pengerjaan'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Final Inspection'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Proses Cuci'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Tunggu Penyerahan'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Proses Cuci'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Final Inspection'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Tunggu Penyerahan'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Proses Pengerjaan'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Proses Cuci'
  },
  { 
    noPolisi: 'B 123 ABC', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    permintaanService: 'General Repair', 
    cuci: false, 
    jamMasuk: '13:30', 
    jamKeluar: '15:00', 
    status: 'Final Inspection'
  },
]

export const progresData = [
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Tunggu Penyerahan',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Proses Pengerjaan',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Final Inspection',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Proses Cuci',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Tunggu Penyerahan',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Proses Pengerjaan',
    estimasiSelesai: '15:00', 
  },
  { 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    namaPelanggan: 'John Doe', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
    status: 'Final Inspection',
    estimasiSelesai: '15:00', 
  },
]

export const welcomeData = [
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
  { 
    jamJanji: '15:00', 
    namaPelanggan: 'John Doe', 
    noPolisi: 'B 123 ABC', 
    permintaanService: 'General Repair', 
    type: 'Kijang Inova', 
    jenisPekerjaan: 'Regular', 
  },
]
